export interface Country {
  code: string;      // ISO 3166-1 alpha-2
  name: string;      // Russian name for UI
  nameEn: string;    // English name (matches TopoJSON name property)
  continent: string; // Continent
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Афганистан", nameEn: "Afghanistan", continent: "Asia" },
  { code: "AL", name: "Албания", nameEn: "Albania", continent: "Europe" },
  { code: "DZ", name: "Алжир", nameEn: "Algeria", continent: "Africa" },
  { code: "AD", name: "Андорра", nameEn: "Andorra", continent: "Europe" },
  { code: "AO", name: "Ангола", nameEn: "Angola", continent: "Africa" },
  { code: "AG", name: "Антигуа и Барбуда", nameEn: "Antigua and Barbuda", continent: "North America" },
  { code: "AR", name: "Аргентина", nameEn: "Argentina", continent: "South America" },
  { code: "AM", name: "Армения", nameEn: "Armenia", continent: "Asia" },
  { code: "AU", name: "Австралия", nameEn: "Australia", continent: "Oceania" },
  { code: "AT", name: "Австрия", nameEn: "Austria", continent: "Europe" },
  { code: "AZ", name: "Азербайджан", nameEn: "Azerbaijan", continent: "Asia" },
  { code: "BS", name: "Багамы", nameEn: "Bahamas", continent: "North America" },
  { code: "BH", name: "Бахрейн", nameEn: "Bahrain", continent: "Asia" },
  { code: "BD", name: "Бангладеш", nameEn: "Bangladesh", continent: "Asia" },
  { code: "BB", name: "Барбадос", nameEn: "Barbados", continent: "North America" },
  { code: "BY", name: "Беларусь", nameEn: "Belarus", continent: "Europe" },
  { code: "BE", name: "Бельгия", nameEn: "Belgium", continent: "Europe" },
  { code: "BZ", name: "Белиз", nameEn: "Belize", continent: "North America" },
  { code: "BJ", name: "Бенин", nameEn: "Benin", continent: "Africa" },
  { code: "BT", name: "Бутан", nameEn: "Bhutan", continent: "Asia" },
  { code: "BO", name: "Боливия", nameEn: "Bolivia", continent: "South America" },
  { code: "BA", name: "Босния и Герцеговина", nameEn: "Bosnia and Herzegovina", continent: "Europe" },
  { code: "BW", name: "Ботсвана", nameEn: "Botswana", continent: "Africa" },
  { code: "BR", name: "Бразилия", nameEn: "Brazil", continent: "South America" },
  { code: "BN", name: "Бруней", nameEn: "Brunei", continent: "Asia" },
  { code: "BG", name: "Болгария", nameEn: "Bulgaria", continent: "Europe" },
  { code: "BF", name: "Буркина-Фасо", nameEn: "Burkina Faso", continent: "Africa" },
  { code: "BI", name: "Бурунди", nameEn: "Burundi", continent: "Africa" },
  { code: "CV", name: "Кабо-Верде", nameEn: "Cabo Verde", continent: "Africa" },
  { code: "KH", name: "Камбоджа", nameEn: "Cambodia", continent: "Asia" },
  { code: "CM", name: "Камерун", nameEn: "Cameroon", continent: "Africa" },
  { code: "CA", name: "Канада", nameEn: "Canada", continent: "North America" },
  { code: "CF", name: "ЦАР", nameEn: "Central African Republic", continent: "Africa" },
  { code: "TD", name: "Чад", nameEn: "Chad", continent: "Africa" },
  { code: "CL", name: "Чили", nameEn: "Chile", continent: "South America" },
  { code: "CN", name: "Китай", nameEn: "China", continent: "Asia" },
  { code: "CO", name: "Колумбия", nameEn: "Colombia", continent: "South America" },
  { code: "KM", name: "Коморы", nameEn: "Comoros", continent: "Africa" },
  { code: "CG", name: "Конго", nameEn: "Congo", continent: "Africa" },
  { code: "CD", name: "ДР Конго", nameEn: "Democratic Republic of the Congo", continent: "Africa" },
  { code: "CR", name: "Коста-Рика", nameEn: "Costa Rica", continent: "North America" },
  { code: "CI", name: "Кот-д'Ивуар", nameEn: "Côte d'Ivoire", continent: "Africa" },
  { code: "HR", name: "Хорватия", nameEn: "Croatia", continent: "Europe" },
  { code: "CU", name: "Куба", nameEn: "Cuba", continent: "North America" },
  { code: "CY", name: "Кипр", nameEn: "Cyprus", continent: "Europe" },
  { code: "CZ", name: "Чехия", nameEn: "Czechia", continent: "Europe" },
  { code: "DK", name: "Дания", nameEn: "Denmark", continent: "Europe" },
  { code: "DJ", name: "Джибути", nameEn: "Djibouti", continent: "Africa" },
  { code: "DM", name: "Доминика", nameEn: "Dominica", continent: "North America" },
  { code: "DO", name: "Доминикана", nameEn: "Dominican Republic", continent: "North America" },
  { code: "EC", name: "Эквадор", nameEn: "Ecuador", continent: "South America" },
  { code: "EG", name: "Египет", nameEn: "Egypt", continent: "Africa" },
  { code: "SV", name: "Сальвадор", nameEn: "El Salvador", continent: "North America" },
  { code: "GQ", name: "Экваториальная Гвинея", nameEn: "Equatorial Guinea", continent: "Africa" },
  { code: "ER", name: "Эритрея", nameEn: "Eritrea", continent: "Africa" },
  { code: "EE", name: "Эстония", nameEn: "Estonia", continent: "Europe" },
  { code: "SZ", name: "Эсватини", nameEn: "Eswatini", continent: "Africa" },
  { code: "ET", name: "Эфиопия", nameEn: "Ethiopia", continent: "Africa" },
  { code: "FJ", name: "Фиджи", nameEn: "Fiji", continent: "Oceania" },
  { code: "FI", name: "Финляндия", nameEn: "Finland", continent: "Europe" },
  { code: "FR", name: "Франция", nameEn: "France", continent: "Europe" },
  { code: "GA", name: "Габон", nameEn: "Gabon", continent: "Africa" },
  { code: "GM", name: "Гамбия", nameEn: "Gambia", continent: "Africa" },
  { code: "GE", name: "Грузия", nameEn: "Georgia", continent: "Asia" },
  { code: "DE", name: "Германия", nameEn: "Germany", continent: "Europe" },
  { code: "GH", name: "Гана", nameEn: "Ghana", continent: "Africa" },
  { code: "GR", name: "Греция", nameEn: "Greece", continent: "Europe" },
  { code: "GD", name: "Гренада", nameEn: "Grenada", continent: "North America" },
  { code: "GT", name: "Гватемала", nameEn: "Guatemala", continent: "North America" },
  { code: "GN", name: "Гвинея", nameEn: "Guinea", continent: "Africa" },
  { code: "GW", name: "Гвинея-Бисау", nameEn: "Guinea-Bissau", continent: "Africa" },
  { code: "GY", name: "Гайана", nameEn: "Guyana", continent: "South America" },
  { code: "HT", name: "Гаити", nameEn: "Haiti", continent: "North America" },
  { code: "HN", name: "Гондурас", nameEn: "Honduras", continent: "North America" },
  { code: "HU", name: "Венгрия", nameEn: "Hungary", continent: "Europe" },
  { code: "IS", name: "Исландия", nameEn: "Iceland", continent: "Europe" },
  { code: "IN", name: "Индия", nameEn: "India", continent: "Asia" },
  { code: "ID", name: "Индонезия", nameEn: "Indonesia", continent: "Asia" },
  { code: "IR", name: "Иран", nameEn: "Iran", continent: "Asia" },
  { code: "IQ", name: "Ирак", nameEn: "Iraq", continent: "Asia" },
  { code: "IE", name: "Ирландия", nameEn: "Ireland", continent: "Europe" },
  { code: "IL", name: "Израиль", nameEn: "Israel", continent: "Asia" },
  { code: "IT", name: "Италия", nameEn: "Italy", continent: "Europe" },
  { code: "JM", name: "Ямайка", nameEn: "Jamaica", continent: "North America" },
  { code: "JP", name: "Япония", nameEn: "Japan", continent: "Asia" },
  { code: "JO", name: "Иордания", nameEn: "Jordan", continent: "Asia" },
  { code: "KZ", name: "Казахстан", nameEn: "Kazakhstan", continent: "Asia" },
  { code: "KE", name: "Кения", nameEn: "Kenya", continent: "Africa" },
  { code: "KI", name: "Кирибати", nameEn: "Kiribati", continent: "Oceania" },
  { code: "KP", name: "Северная Корея", nameEn: "North Korea", continent: "Asia" },
  { code: "KR", name: "Южная Корея", nameEn: "South Korea", continent: "Asia" },
  { code: "KW", name: "Кувейт", nameEn: "Kuwait", continent: "Asia" },
  { code: "KG", name: "Киргизия", nameEn: "Kyrgyzstan", continent: "Asia" },
  { code: "LA", name: "Лаос", nameEn: "Laos", continent: "Asia" },
  { code: "LV", name: "Латвия", nameEn: "Latvia", continent: "Europe" },
  { code: "LB", name: "Ливан", nameEn: "Lebanon", continent: "Asia" },
  { code: "LS", name: "Лесото", nameEn: "Lesotho", continent: "Africa" },
  { code: "LR", name: "Либерия", nameEn: "Liberia", continent: "Africa" },
  { code: "LY", name: "Ливия", nameEn: "Libya", continent: "Africa" },
  { code: "LI", name: "Лихтенштейн", nameEn: "Liechtenstein", continent: "Europe" },
  { code: "LT", name: "Литва", nameEn: "Lithuania", continent: "Europe" },
  { code: "LU", name: "Люксембург", nameEn: "Luxembourg", continent: "Europe" },
  { code: "MG", name: "Мадагаскар", nameEn: "Madagascar", continent: "Africa" },
  { code: "MW", name: "Малави", nameEn: "Malawi", continent: "Africa" },
  { code: "MY", name: "Малайзия", nameEn: "Malaysia", continent: "Asia" },
  { code: "MV", name: "Мальдивы", nameEn: "Maldives", continent: "Asia" },
  { code: "ML", name: "Мали", nameEn: "Mali", continent: "Africa" },
  { code: "MT", name: "Мальта", nameEn: "Malta", continent: "Europe" },
  { code: "MR", name: "Мавритания", nameEn: "Mauritania", continent: "Africa" },
  { code: "MU", name: "Маврикий", nameEn: "Mauritius", continent: "Africa" },
  { code: "MX", name: "Мексика", nameEn: "Mexico", continent: "North America" },
  { code: "FM", name: "Микронезия", nameEn: "Micronesia", continent: "Oceania" },
  { code: "MD", name: "Молдова", nameEn: "Moldova", continent: "Europe" },
  { code: "MC", name: "Монако", nameEn: "Monaco", continent: "Europe" },
  { code: "MN", name: "Монголия", nameEn: "Mongolia", continent: "Asia" },
  { code: "ME", name: "Черногория", nameEn: "Montenegro", continent: "Europe" },
  { code: "MA", name: "Марокко", nameEn: "Morocco", continent: "Africa" },
  { code: "MZ", name: "Мозамбик", nameEn: "Mozambique", continent: "Africa" },
  { code: "MM", name: "Мьянма", nameEn: "Myanmar", continent: "Asia" },
  { code: "NA", name: "Намибия", nameEn: "Namibia", continent: "Africa" },
  { code: "NR", name: "Науру", nameEn: "Nauru", continent: "Oceania" },
  { code: "NP", name: "Непал", nameEn: "Nepal", continent: "Asia" },
  { code: "NL", name: "Нидерланды", nameEn: "Netherlands", continent: "Europe" },
  { code: "NZ", name: "Новая Зеландия", nameEn: "New Zealand", continent: "Oceania" },
  { code: "NI", name: "Никарагуа", nameEn: "Nicaragua", continent: "North America" },
  { code: "NE", name: "Нигер", nameEn: "Niger", continent: "Africa" },
  { code: "NG", name: "Нигерия", nameEn: "Nigeria", continent: "Africa" },
  { code: "MK", name: "Северная Македония", nameEn: "North Macedonia", continent: "Europe" },
  { code: "NO", name: "Норвегия", nameEn: "Norway", continent: "Europe" },
  { code: "OM", name: "Оман", nameEn: "Oman", continent: "Asia" },
  { code: "PK", name: "Пакистан", nameEn: "Pakistan", continent: "Asia" },
  { code: "PW", name: "Палау", nameEn: "Palau", continent: "Oceania" },
  { code: "PA", name: "Панама", nameEn: "Panama", continent: "North America" },
  { code: "PG", name: "Папуа — Новая Гвинея", nameEn: "Papua New Guinea", continent: "Oceania" },
  { code: "PY", name: "Парагвай", nameEn: "Paraguay", continent: "South America" },
  { code: "PE", name: "Перу", nameEn: "Peru", continent: "South America" },
  { code: "PH", name: "Филиппины", nameEn: "Philippines", continent: "Asia" },
  { code: "PL", name: "Польша", nameEn: "Poland", continent: "Europe" },
  { code: "PT", name: "Португалия", nameEn: "Portugal", continent: "Europe" },
  { code: "QA", name: "Катар", nameEn: "Qatar", continent: "Asia" },
  { code: "RO", name: "Румыния", nameEn: "Romania", continent: "Europe" },
  { code: "RU", name: "Россия", nameEn: "Russia", continent: "Europe" },
  { code: "RW", name: "Руанда", nameEn: "Rwanda", continent: "Africa" },
  { code: "KN", name: "Сент-Китс и Невис", nameEn: "Saint Kitts and Nevis", continent: "North America" },
  { code: "LC", name: "Сент-Люсия", nameEn: "Saint Lucia", continent: "North America" },
  { code: "VC", name: "Сент-Винсент и Гренадины", nameEn: "Saint Vincent and the Grenadines", continent: "North America" },
  { code: "WS", name: "Самоа", nameEn: "Samoa", continent: "Oceania" },
  { code: "SM", name: "Сан-Марино", nameEn: "San Marino", continent: "Europe" },
  { code: "ST", name: "Сан-Томе и Принсипи", nameEn: "São Tomé and Príncipe", continent: "Africa" },
  { code: "SA", name: "Саудовская Аравия", nameEn: "Saudi Arabia", continent: "Asia" },
  { code: "SN", name: "Сенегал", nameEn: "Senegal", continent: "Africa" },
  { code: "RS", name: "Сербия", nameEn: "Serbia", continent: "Europe" },
  { code: "SC", name: "Сейшелы", nameEn: "Seychelles", continent: "Africa" },
  { code: "SL", name: "Сьерра-Леоне", nameEn: "Sierra Leone", continent: "Africa" },
  { code: "SG", name: "Сингапур", nameEn: "Singapore", continent: "Asia" },
  { code: "SK", name: "Словакия", nameEn: "Slovakia", continent: "Europe" },
  { code: "SI", name: "Словения", nameEn: "Slovenia", continent: "Europe" },
  { code: "SB", name: "Соломоновы Острова", nameEn: "Solomon Islands", continent: "Oceania" },
  { code: "SO", name: "Сомали", nameEn: "Somalia", continent: "Africa" },
  { code: "ZA", name: "ЮАР", nameEn: "South Africa", continent: "Africa" },
  { code: "SS", name: "Южный Судан", nameEn: "South Sudan", continent: "Africa" },
  { code: "ES", name: "Испания", nameEn: "Spain", continent: "Europe" },
  { code: "LK", name: "Шри-Ланка", nameEn: "Sri Lanka", continent: "Asia" },
  { code: "SD", name: "Судан", nameEn: "Sudan", continent: "Africa" },
  { code: "SR", name: "Суринам", nameEn: "Suriname", continent: "South America" },
  { code: "SE", name: "Швеция", nameEn: "Sweden", continent: "Europe" },
  { code: "CH", name: "Швейцария", nameEn: "Switzerland", continent: "Europe" },
  { code: "SY", name: "Сирия", nameEn: "Syria", continent: "Asia" },
  { code: "TW", name: "Тайвань", nameEn: "Taiwan", continent: "Asia" },
  { code: "TJ", name: "Таджикистан", nameEn: "Tajikistan", continent: "Asia" },
  { code: "TZ", name: "Танзания", nameEn: "Tanzania", continent: "Africa" },
  { code: "TH", name: "Таиланд", nameEn: "Thailand", continent: "Asia" },
  { code: "TL", name: "Восточный Тимор", nameEn: "Timor-Leste", continent: "Asia" },
  { code: "TG", name: "Того", nameEn: "Togo", continent: "Africa" },
  { code: "TO", name: "Тонга", nameEn: "Tonga", continent: "Oceania" },
  { code: "TT", name: "Тринидад и Тобаго", nameEn: "Trinidad and Tobago", continent: "North America" },
  { code: "TN", name: "Тунис", nameEn: "Tunisia", continent: "Africa" },
  { code: "TR", name: "Турция", nameEn: "Turkey", continent: "Asia" },
  { code: "TM", name: "Туркменистан", nameEn: "Turkmenistan", continent: "Asia" },
  { code: "TV", name: "Тувалу", nameEn: "Tuvalu", continent: "Oceania" },
  { code: "UG", name: "Уганда", nameEn: "Uganda", continent: "Africa" },
  { code: "UA", name: "Украина", nameEn: "Ukraine", continent: "Europe" },
  { code: "AE", name: "ОАЭ", nameEn: "United Arab Emirates", continent: "Asia" },
  { code: "GB", name: "Великобритания", nameEn: "United Kingdom", continent: "Europe" },
  { code: "US", name: "США", nameEn: "United States", continent: "North America" },
  { code: "UY", name: "Уругвай", nameEn: "Uruguay", continent: "South America" },
  { code: "UZ", name: "Узбекистан", nameEn: "Uzbekistan", continent: "Asia" },
  { code: "VU", name: "Вануату", nameEn: "Vanuatu", continent: "Oceania" },
  { code: "VE", name: "Венесуэла", nameEn: "Venezuela", continent: "South America" },
  { code: "VN", name: "Вьетнам", nameEn: "Vietnam", continent: "Asia" },
  { code: "YE", name: "Йемен", nameEn: "Yemen", continent: "Asia" },
  { code: "ZM", name: "Замбия", nameEn: "Zambia", continent: "Africa" },
  { code: "ZW", name: "Зимбабве", nameEn: "Zimbabwe", continent: "Africa" },
  { code: "XK", name: "Косово", nameEn: "Kosovo", continent: "Europe" },
];

/** Total countries in the list (used for stats) */
export const TOTAL_COUNTRIES = 194;

export const CONTINENTS = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
] as const;

export type Continent = (typeof CONTINENTS)[number];

/** Russian labels for continents (map filters, stats) */
export const CONTINENT_LABELS: Record<string, string> = {
  Africa: "Африка",
  Asia: "Азия",
  Europe: "Европа",
  "North America": "Северная Америка",
  "South America": "Южная Америка",
  Oceania: "Океания",
};

/** Map tooltip: TopoJSON English names for territories → Russian (not in COUNTRIES) */
export const GEO_NAME_TO_RU: Record<string, string> = {
  "Greenland": "Гренландия",
  "N. Cyprus": "Северный Кипр",
  "S. Sudan": "Южный Судан",
  "Fr. S. Antarctic Lands": "Французские Южные территории",
  "Falkland Is.": "Фолклендские острова",
  "Br. Indian Ocean Ter.": "Британская территория в Индийском океане",
  "W. Sahara": "Западная Сахара",
  "Antarctica": "Антарктида",
};

/** Map region: world view or a single continent */
export type MapRegion = "World" | Continent;

/** Viewport preset: center [lon, lat] and zoom for ZoomableGroup */
export interface MapViewportPreset {
  center: [number, number];
  zoom: number;
}

/** Viewport presets for map region filter (center and zoom per region) */
export const MAP_VIEWPORT_PRESETS: Record<MapRegion, MapViewportPreset> = {
  World: { center: [0, 20], zoom: 1 },
  Europe: { center: [15, 54], zoom: 2.5 },
  Asia: { center: [100, 34], zoom: 2 },
  Africa: { center: [20, 0], zoom: 2.2 },
  "North America": { center: [-100, 45], zoom: 2 },
  "South America": { center: [-60, -15], zoom: 2.2 },
  Oceania: { center: [135, -25], zoom: 2.5 },
};

/** Lookup: alpha-2 code → Country object */
export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c])
);
